
pipeline {
    agent any
    stages {
        stage('Compile') {
            steps {
                dir('play-with-devops-tools/calculation-service') {
                    sh 'mvn clean compile'
                }
            }
        }
        stage('Unit Test') {
            steps {
                echo "Unit Test"
            }
        }
        stage('Integration Test') {
            steps {
                echo "Integration Test"
            }
        }
        stage('API Test') {
            steps {
                echo "API Test"
            }
        }
    }
}