
pipeline {
    agent any
    stages {
        stage('Compile') {
            steps {
                dir('play-with-devops-tools/calculation-service') {
                    sh 'mvn clean compile'
                }
            }
        }
        stage('Unit Test') {
            steps {
                dir('play-with-devops-tools/calculation-service') {
                    sh 'mvn test -Punit-tests'
                }
            }
        }
        stage('Integration Test') {
            steps {
                dir('play-with-devops-tools/calculation-service') {
                    sh 'mvn test -Pintegration-tests'
                }
            }
        }
        stage('API Test') {
            steps {
                dir('play-with-devops-tools/calculation-service') {
                    sh 'mvn test -Papi-tests'
                }
            }
        }
        stage('Build/Package') {
            steps {
                dir('play-with-devops-tools/calculation-service') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
    }
}